language: java

services:
  - mysql

jdk:
  - oraclejdk7
  - oraclejdk8

install:
  - mkdir -p download
  - src/test/bash/create_certificates.sh
  - src/test/bash/install_vault.sh
  - src/test/bash/local_run_vault.sh &

before_script:
  - mysql -e "CREATE USER 'spring' IDENTIFIED by 'vault';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'spring'@'%' WITH GRANT OPTION;";
  - source src/test/bash/env.sh && src/test/bash/setup_examples.sh

script: mvn clean verify

after_script:
  - pkill vault

cache:
  directories:
    - '$HOME/.m2/repository'
    - 'download'
